version: '3.7'
services:      
  jenkins:
    container_name: jenkins_server
    build: docker/build/jenkins
    healthcheck:
        test: ["CMD", "wget", "http://localhost:${JENKINS_SERVER_PORT}/login"]
        interval: 30s
        timeout: 10s
        retries: 5
    ports:
      - "${JENKINS_SERVER_PORT}:8080"
    volumes:
      - jenkinsServerVolume:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    user: root
    environment:
      - JENKINS_ADMIN_USER
      - JENKINS_ADMIN_PASS
      - JENKINS_ADMIN_ADDR
      - JENKINS_SERVER_PORT
      - JENKINS_IMAGE_VERSION
      - JENKINS_DATA_DIR
      - JENKINS_EXECUTORS
      - JENKINS_GIT_NAME
      - JENKINS_GIT_EMAIL
      - JENKINS_SLAVE_AGENT_PORT
      - JENKINS_QUIET_PERIOD
    labels:
      - "com.efx.jenkins.description=Jenkins Master Server"
      - "com.efx.jenkins.deparment=dev"
      - "com.efx.jenkins.node_type=master"

volumes:
  jenkinsServerVolume: